### ISSUE TITLE
Make hashing algorithm customizable?

### ISSUE THREAD

**Issue by bkosborne** [8p/guzzle-wsse-middleware#2]
Currently it's hardcoded to `sha1`, but I think `sha256` or `sha512` is more secure. I'm not sure if this breaks the WSSE protocol spec or not, but it seems reasonable to make this customizable so the bundle can easily adapt to better hashing algorithms.

**Comment by gregurco** [comment]
As I found, sha1 is unique allowed encoding:
```
Passwords of type PasswordDigest are defined as being the Base64 [XML-Schema] encoded, SHA-1 hash value, of the UTF8 encoded password (or equivalent).

Password_Digest = Base64 ( SHA-1 ( nonce + created + password ) )
```
Link: https://www.oasis-open.org/committees/download.php/13392/wss-v1.1-spec-pr-UsernameTokenProfile-01.htm

And I think it's obvious, because server should know how to check PasswordDigest and we don't send encoding type to the server. I think issue can be closed.
